services:
  - type: web
    name: tribo-do-cerrado-social
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'php index.php'
    staticPublishPath: 'public'
    buildFilter:
      paths:
        - '**/*'
    envVars:
      - key: NODE_ENV
        value: production
