services:
  - type: web
    name: tribodocerrado
    runtime: docker
    plan: free
    repo: https://github.com/rodrigorochalima/tribodocerrado.git
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://triboadmin:8xFUEgRCb3cIU0Oz7GtZmmRPr3QXMWAJ@dpg-d14cdmh5pdvs73f1njd0-a/tribodocerrado
      - key: YII_ENV
        value: prod
      - key: YII_DEBUG
        value: false

